apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
      domain: tracing
      component: monitoring
  namespaceSelector:
    matchNames:
      - tracing
  endpoints:
    - port: admin-http
      interval: 15s
      scrapeTimeout: 14s
