
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - rbac.yaml
  - daemonset.yaml
  - service.yaml
  - svc-monitor.yaml

configMapGenerator:
  - name: vector-agent-managed
    files:
      - managed.toml
  - name: vector-agent-config
    files:
      - vector-agent.toml

generatorOptions:
  # Avoid a suffix at the `ConfigMap` name
  disableNameSuffixHash: true

commonLabels:
  app: vector-agent
  domain: logging
  feature: vector
  # vector specific
  vector.dev/exclude: "true"

commonAnnotations:
  version: "0.11.1-debian"
  # version: "0.11.1-alpine"
