apiVersion: v1
kind: Service
metadata:
  name: vector-agent
spec:
  selector:
    app: vector-agent
  ports:
    - name: api
      port: 8686
      targetPort: api
    - name: metrics
      port: 9090
      targetPort: metrics
