apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vector-agent
spec:
  selector:
    matchLabels:
      app: vector-agent
      domain: logging
      feature: vector
  namespaceSelector:
    matchNames:
      - logging
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 14s
