apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer
data:
  # logging
  LOG_ENCODING: json

  # tracing
  ## jaeger general
  JAEGER_SERVICE_NAME: kafka-producer
  JAEGER_SAMPLER_TYPE: const
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_REPORTER_LOG_SPANS: "true"
  JAEGER_REPORTER_FLUSH_INTERVAL: 1s
  JAEGER_AGENT_PORT: "6831"
  ## grafana-tempo
  JAEGER_AGENT_HOST: tempo.tracing.svc.cluster.local
  ## jaeger
  ### agent
  # JAEGER_AGENT_HOST: jaeger-agent.tracing.svc.cluster.local
  ### bypass agent, directly to collector
  # JAEGER_ENDPOINT: http://jaeger-collector.tracing.svc.cluster.local:14268/api/traces

  # kafka
  KAFKA_BOOTSTRAP_SERVERS: strimzi-kafka-bootstrap.kafka.svc.cluster.local
  KAFKA_PORT: "9092"
  KAFKA_TOPIC: my-topic
