apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-producer
spec:
  selector:
    matchLabels:
      app: kafka-producer
  namespaceSelector:
    matchNames:
      - apps
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 14s
