apiVersion: apps/v1
kind: Deployment
metadata:
  name: standalone
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standalone
  template:
    metadata:
      labels:
        app: standalone
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: standalone
          image: bygui86/standalone:v1.0.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: standalone
#          ports:
#            - name: metrics
#              containerPort: 9090
#             - name: probes
#               containerPort: 9091
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          # livenessProbe:
          #   httpGet:
          #     path: /live
          #     port: probes
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: probes
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   successThreshold: 1
          #   failureThreshold: 3
