
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - configmap.yaml
  - deployment.yaml

commonLabels:
  app: standalone
  domain: apps

commonAnnotations:
  version: v1.0.0
