apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
data:
  GF_INSTALL_PLUGINS: "grafana-kubernetes-app,camptocamp-prometheus-alertmanager-datasource,grafana-piechart-panel,grafana-polystat-panel,agenty-flowcharting-panel,marcusolsson-hexmap-panel"
  
  # datasources
  PROMETHEUS_URL: "http://prometheus.monitoring.svc.cluster.local:9090"
  LOKI_URL: "http://loki.logging.svc.cluster.local:3100"
  LOKI_PROMETHEUS_URL: "http://loki.logging.svc.cluster.local:3100/loki"
  JAEGER_URL: "http://jaeger-query.tracing.svc.cluster.local:16686"
  # TEMPO_URL: "http://tempo.tracing.svc.cluster.local:16686"
