
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - svc-monitor.yaml

configMapGenerator:
  - name: grafana-datasources
    files:
      - datasources.yaml
  - name: grafana-dashboards
    files:
      - dashboards.yaml

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  component: grafana

# WARN: remember to keep dashboard/kustomization.yaml aligned with all changes made in this file
