apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
    - name: http-metrics
      port: 3100
      targetPort: http-metrics
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  labels:
    headless: "true"
spec:
  clusterIP: None
  selector:
    app: loki
  ports:
    - name: http-metrics
      port: 3100
      targetPort: http-metrics
      protocol: TCP
