apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-db
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-db
  template:
    metadata:
      labels:
        app: http-server-db
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: http-server-db
          image: bygui86/http-server-db:v1.0.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: http-server-db
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9090
            # - name: probes
            #   containerPort: 9091
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          # livenessProbe:
          #   httpGet:
          #     path: /live
          #     port: probes
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: probes
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   successThreshold: 1
          #   failureThreshold: 3
