apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: http-server-db
spec:
  selector:
    matchLabels:
      app: http-server-db
  namespaceSelector:
    matchNames:
      - apps
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 14s
