apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  labels:
    app: grafana
data:
  GF_INSTALL_PLUGINS: "grafana-kubernetes-app,camptocamp-prometheus-alertmanager-datasource,grafana-piechart-panel,grafana-polystat-panel,agenty-flowcharting-panel"
  
  # datasources
  PROMETHEUS_URL: "http://prometheus.monitoring.svc.cluster.local:9090"
  LOKI_URL: "http://loki.logging.svc.cluster.local:3100"
  LOKI_PROMETHEUS_URL: "http://loki.logging.svc.cluster.local:3100/loki"
  TEMPO_URL: "https://tempo.tracing.svc.cluster.local:16686"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |-
    apiVersion: 1

    datasources:

    # - name: prometheus
    #   uid: prometheus
    #   type: prometheus
    #   orgId: 1
    #   url: $PROMETHEUS_URL
    #   access: proxy
    #   isDefault: true
    #   version: 1
    #   editable: true

    # - name: loki
    #   uid: loki
    #   type: loki
    #   orgId: 1
    #   url: $LOKI_URL
    #   access: proxy
    #   isDefault: false
    #   version: 1
    #   editable: true
    #   jsonData:
    #     # https://grafana.com/docs/grafana/latest/datasources/loki/#derived-fields
    #     # https://grafana.com/docs/tempo/latest/guides/loki-derived-fields/
    #     derivedFields:
    #       - datasourceUid: tempo
    #         matcherRegex: (?:traceID|trace_id)=(\w+)
    #         name: TraceID
    #         url: $${__value.raw}

    # - name: loki-prometheus
    #   uid: loki-prometheus
    #   type: prometheus
    #   orgId: 1
    #   url: $LOKI_PROMETHEUS_URL
    #   access: proxy
    #   isDefault: false
    #   version: 1
    #   editable: true

    - name: tempo
      uid: tempo
      type: tempo
      orgId: 1
      url: $TEMPO_URL
      access: proxy
      isDefault: false
      version: 1
      editable: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  dashboards.yaml: |-
    apiVersion: 1

    providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 300
        options:
          path: "/etc/dashboards"
          foldersFromFilesStructure: true
