{
 "title": "Tempo - Operational",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "logsds", "query": "loki" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tempo_build_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\".*tempo.*\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "component",
    "query": "compactor,distributor,ingester,querier,cortex-gw"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gcs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "go heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$component.*\", container!=\"POD\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "working set",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$component.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "tx/rx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$component.*\"}[$__rate_interval])",
     "legendFormat": "rx-{{pod}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$component.*\"}[$__rate_interval])",
     "legendFormat": "tx-{{pod}}"
    }
   ]
  },
  {
   "title": "data volume free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"$component.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "bad words",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promtail_custom_bad_words_total{cluster=\"$cluster\", exported_namespace=\"$namespace\", app=~\"$component.*\"}[$__rate_interval])",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  { "title": "Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "%age total work queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "tempodb_work_queue_length{job=~\"$namespace/$component\"} / tempodb_work_queue_max{job=~\"$namespace/$component\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "maintenance errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tempodb_compaction_errors_total{job=~\"$namespace/$component\"}[$__rate_interval])) by (job)",
     "legendFormat": "compaction_err"
    },
    {
     "expr": "sum(increase(tempodb_retention_errors_total{job=~\"$namespace/$component\"}[$__rate_interval])) by (job)",
     "legendFormat": "retention_err"
    },
    {
     "expr": "sum(increase(tempodb_blocklist_poll_errors_total{job=~\"$namespace/$component\"}[$__rate_interval])) by (job)",
     "legendFormat": "blocklist_err"
    }
   ]
  },
  {
   "title": "Blocklist Poll Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{job=~\"$namespace/$component\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{job=~\"$namespace/$component\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{job=~\"$namespace/$component\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Blocklist Length",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tempodb_blocklist_length{job=~\"$namespace/$component\"}) by (tenant)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "retention duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempodb_retention_duration_seconds_bucket{job=~\"$namespace/compactor\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_retention_duration_seconds_bucket{job=~\"$namespace/compactor\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_retention_duration_seconds_bucket{job=~\"$namespace/compactor\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "retention",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tempodb_retention_deleted_total{job=~\"$namespace/$component\"}[$__rate_interval]))",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(increase(tempodb_retention_marked_for_deletion_total{job=~\"$namespace/$component\"}[$__rate_interval]))",
     "legendFormat": "marked_for_deletion"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Queries/Sec (Query Frontend)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=\"api_traces_traceid\", job=\"$namespace/query-frontend\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Query Latency (Gateway)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/cortex-gw\", route=\"tempo_api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/cortex-gw\", route=\"tempo_api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/cortex-gw\", route=\"tempo_api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Query Latency (Query Frontend)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/query-frontend\", route=\"api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/query-frontend\", route=\"api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/query-frontend\", route=\"api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Query Latency (Querier)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/querier\", route=\"querier_api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/querier\", route=\"querier_api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/querier\", route=\"querier_api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Query  Bytes Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_query_bytes_read_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_query_bytes_read_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_query_bytes_read_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Query Latency (Ingester)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/ingester\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/ingester\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/ingester\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "p50 Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_query_reads_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (layer, le))",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  {
   "title": "p99 Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_query_reads_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (layer, le))",
     "legendFormat": "{{layer}}"
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Spans Received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_distributor_spans_received_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Traces Created",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_ingester_traces_created_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Flushed (1h)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tempo_ingester_blocks_flushed_total{job=\"$namespace/ingester\"}[1h]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Flushes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tempo_ingester_failed_flushes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Blocks Cleared (1h)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tempo_ingester_blocks_cleared_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1h]))"
    }
   ]
  },
  {
   "title": "Flush Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_ingester_flush_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_ingester_flush_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_ingester_flush_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Pushes/sec (gateway)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{job=\"$namespace/cortex-gw\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "OTEL Distributor Spans/second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_receiver_accepted_spans{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(tempo_receiver_refused_spans{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "refused"
    }
   ]
  },
  {
   "title": "Push Latency (Gateway)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/cortex-gw\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/cortex-gw\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/cortex-gw\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Push Latency (Ingester)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/ingester\", route=\"/tempopb.Pusher/Push\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/ingester\", route=\"/tempopb.Pusher/Push\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$namespace/ingester\", route=\"/tempopb.Pusher/Push\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  { "title": "Memcached", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Requests/Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_memcache_request_duration_seconds_count{job=~\"$namespace/$component\"}[$__rate_interval])) by (status_code, method)",
     "legendFormat": "{{status_code}}-{{method}}"
    }
   ]
  },
  {
   "title": "Latency By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(cortex_memcache_request_duration_seconds_bucket{job=~\"$namespace/$component\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".99-{{method}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(cortex_memcache_request_duration_seconds_bucket{job=~\"$namespace/$component\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".9-{{method}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(cortex_memcache_request_duration_seconds_bucket{job=~\"$namespace/$component\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".5-{{method}}"
    }
   ]
  },
  {
   "title": "GCS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tempodb_gcs_request_duration_seconds_count{job=~\"$namespace/$component\"}[$__rate_interval])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    },
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempodb_gcs_request_duration_seconds_bucket{job=~\"$namespace/$component\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempodb_gcs_request_duration_seconds_bucket{job=~\"$namespace/$component\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempodb_gcs_request_duration_seconds_bucket{job=~\"$namespace/$component\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ring/Memberlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossip Health",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gauge_memberlist_health_score{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Health",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tempo_memberlist_client_cluster_node_health_score{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Member Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min(tempo_memberlist_client_cluster_members_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"})",
       "legendFormat": "min"
      },
      {
       "expr": "max(tempo_memberlist_client_cluster_members_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "KV Store Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min(tempo_memberlist_client_kv_store_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"})",
       "legendFormat": "min"
      },
      {
       "expr": "max(tempo_memberlist_client_kv_store_count{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  { "title": "Vulture", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Traces Not Found",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tempo_vulture_trace_error_total{cluster=\"$cluster\", namespace=\"$namespace\", error=\"notfound\"}[1h])) by (secondsago) / sum(rate(tempo_vulture_trace_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1h])) by (secondsago)",
     "legendFormat": "{{secondsago}}"
    }
   ]
  },
  {
   "title": "Traces Missing Spans",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(tempo_vulture_trace_error_total{cluster=\"$cluster\", namespace=\"$namespace\", error=\"missingspans\"}[1h])) by (secondsago) / sum(rate(tempo_vulture_trace_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1h])) by (secondsago)",
     "legendFormat": "{{secondsago}}"
    }
   ]
  },
  { "title": "Compactor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Objects Combined / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_objects_combined_total{cluster=\"$cluster\",job=~\"$namespace/compactor\"}[$__rate_interval])) by (level)"
    }
   ]
  },
  {
   "title": "Objects Written / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_objects_written{cluster=\"$cluster\",job=\"$namespace/compactor\"}[$__rate_interval])) by (level)"
    }
   ]
  },
  {
   "title": "Bytes Written / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_bytes_written{cluster=\"$cluster\",job=\"$namespace/compactor\"}[$__rate_interval])) by (level)"
    }
   ]
  },
  {
   "title": "Blocks Compacted",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tempodb_compaction_blocks_total{cluster=\"$cluster\",job=\"$namespace/compactor\"}[5m])) by (level)"
    }
   ]
  }
 ]
}