{
 "title": "Kubemq",
 "tags": [
  "brokers",
  "kubemq"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "channelType",
    "label": "ChannelType",
    "query": "events,events_store,queues,queries,commands"
   }
  ]
 },
 "panels": [
  { "title": "Incoming overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total incoming messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{side=\"send\"})"
    }
   ]
  },
  {
   "title": "Total incoming volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubemq_messages_volume{side=\"send\"})"
    }
   ]
  },
  {
   "title": "Total incoming errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubemq_messages_errors{side=\"send\"})"
    }
   ]
  },
  {
   "title": "Incoming message rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Messages per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubemq_messages_count{side=\"send\"}[1m])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming volume rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bps", "label": "Volume per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubemq_messages_volume{side=\"send\"}[1m])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming errors rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Errors per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubemq_messages_errors{side=\"send\"}[1m])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Pending overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total pending incoming messages",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubemq_messages_pending{side=\"send\"})"
      }
     ]
    },
    {
     "title": "Total pending outgoing messages",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubemq_messages_pending{side=\"receive\"})"
      }
     ]
    },
    {
     "title": "Pending incoming message rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Messages per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_pending{side=\"send\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Pending outgoing message rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Messages per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_pending{side=\"receive\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  { "title": "Outgoing overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total outgoing messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{side=\"receive\"})"
    }
   ]
  },
  {
   "title": "Total outgoing volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubemq_messages_volume{side=\"receive\"})"
    }
   ]
  },
  {
   "title": "Total outgoing errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubemq_messages_errors{side=\"receive\"})"
    }
   ]
  },
  {
   "title": "Outgoing message rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Messages per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubemq_messages_count{side=\"receive\"}[1m])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Outgoing volume rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bps", "label": "Volume per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubemq_messages_volume{side=\"receive\"}[1m])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Outgoing errors rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Errors per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubemq_messages_errors{side=\"receive\"}[1m])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "$channelType",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "channelType",
   "collapsed": true,
   "panels": [
    {
     "title": "$channelType - Incoming messages rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_count{side=\"send\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Incoming volume rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_volume{side=\"send\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Outgoing messages rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_count{side=\"receive\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Outgoing volume rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_volume{side=\"receive\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Clients",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(kubemq_messages_count{type=\"$channelType\"}) by(client_id,side) "
      },
      {
       "expr": "sum(kubemq_messages_volume{type=\"$channelType\"}) by(client_id,side)"
      }
     ]
    },
    {
     "title": "$channelType - Channels",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(kubemq_messages_count{type=\"$channelType\"}) by(channel,side) "
      },
      {
       "expr": "sum(kubemq_messages_volume{type=\"$channelType\"}) by(channel,side) "
      }
     ]
    }
   ]
  },
  {
   "title": "$channelType",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "$channelType - Incoming messages rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_count{side=\"send\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Incoming volume rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_volume{side=\"send\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Outgoing messages rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_count{side=\"receive\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Outgoing volume rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_volume{side=\"receive\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Clients",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(kubemq_messages_count{type=\"$channelType\"}) by(client_id,side) "
      },
      {
       "expr": "sum(kubemq_messages_volume{type=\"$channelType\"}) by(client_id,side)"
      }
     ]
    },
    {
     "title": "$channelType - Channels",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(kubemq_messages_count{type=\"$channelType\"}) by(channel,side) "
      },
      {
       "expr": "sum(kubemq_messages_volume{type=\"$channelType\"}) by(channel,side) "
      }
     ]
    }
   ]
  },
  {
   "title": "$channelType",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$channelType - Incoming messages rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_count{side=\"send\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Incoming volume rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_volume{side=\"send\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Outgoing messages rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_count{side=\"receive\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Outgoing volume rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_volume{side=\"receive\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Clients",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(kubemq_messages_count{type=\"$channelType\"}) by(client_id,side) "
      },
      {
       "expr": "sum(kubemq_messages_volume{type=\"$channelType\"}) by(client_id,side)"
      }
     ]
    },
    {
     "title": "$channelType - Channels",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(kubemq_messages_count{type=\"$channelType\"}) by(channel,side) "
      },
      {
       "expr": "sum(kubemq_messages_volume{type=\"$channelType\"}) by(channel,side) "
      }
     ]
    }
   ]
  },
  {
   "title": "$channelType",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "$channelType - Incoming messages rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_count{side=\"send\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Incoming volume rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_volume{side=\"send\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Outgoing messages rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_count{side=\"receive\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Outgoing volume rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_volume{side=\"receive\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Clients",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(kubemq_messages_count{type=\"$channelType\"}) by(client_id,side) "
      },
      {
       "expr": "sum(kubemq_messages_volume{type=\"$channelType\"}) by(client_id,side)"
      }
     ]
    },
    {
     "title": "$channelType - Channels",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(kubemq_messages_count{type=\"$channelType\"}) by(channel,side) "
      },
      {
       "expr": "sum(kubemq_messages_volume{type=\"$channelType\"}) by(channel,side) "
      }
     ]
    }
   ]
  },
  {
   "title": "$channelType",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "$channelType - Incoming messages rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_count{side=\"send\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Incoming volume rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_volume{side=\"send\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Outgoing messages rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_count{side=\"receive\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Outgoing volume rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kubemq_messages_volume{side=\"receive\",type=\"$channelType\"}[1m]))"
      }
     ]
    },
    {
     "title": "$channelType - Clients",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(kubemq_messages_count{type=\"$channelType\"}) by(client_id,side) "
      },
      {
       "expr": "sum(kubemq_messages_volume{type=\"$channelType\"}) by(client_id,side)"
      }
     ]
    },
    {
     "title": "$channelType - Channels",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(kubemq_messages_count{type=\"$channelType\"}) by(channel,side) "
      },
      {
       "expr": "sum(kubemq_messages_volume{type=\"$channelType\"}) by(channel,side) "
      }
     ]
    }
   ]
  }
 ]
}