apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prod
spec:
  # v2.23.0
  image: quay.io/prometheus/prometheus:v2.23.0@sha256:0eac377a90d361be9da35b469def699bcd5bb26eab8a6e9068516a9910717d58
  replicas: 1

  logFormat: json
  logLevel: info
  
  resources:
    requests:
      cpu: "1"
      memory: 1G
    limits:
      cpu: "1"
      memory: 1G
  
  # How long to retain samples in storage.
  # Overrides "storage.tsdb.retention" if this flag is set to anything other than default.
  retention: 1d
  # [EXPERIMENTAL] Maximum number of bytes that can be stored for blocks. 
  # Units supported: KB, MB, GB, TB, PB. This flag is experimental and can be changed in future releases.
  retentionSize: 500MB

  serviceAccountName: prometheus

  securityContext:
    runAsUser: 1001
    fsGroup: 1001

  podMetadata:
    name: prometheus
    labels:
      # INFO: reserved for operating
      # app: prometheus
      # WARN: not added by the operator in version 0.3x.x
      domain: monitoring
      feature: prometheus

  alerting:
    alertmanagers:
      - name: alertmanager
        namespace: monitoring
        port: web

  # empty = all
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      # app: prometheus
      # domain: monitoring
      role: alert-rules

  # empty = all
  podMonitorNamespaceSelector: {}
  # empty = no label selector
  podMonitorSelector: {}

  # empty = all
  serviceMonitorNamespaceSelector: {}
  # empty = no label selector
  serviceMonitorSelector: {}
  
  # additionalScrapeConfigs:
  #   name: prometheus-additional
  #   key: prometheus-additional.yaml
  
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus
        labels:
          # INFO: reserved for operating
          # app: prometheus
          # WARN: not added by the operator in version 0.3x.x
          domain: monitoring
          feature: prometheus
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
