
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - crds.yaml
  - kubemqclusters.yaml
  - kubemqconnectors.yaml
  - kubemqdashboards.yaml

commonLabels:
  app: kubemq-operator
  domain: brokers
  group: crds

commonAnnotations:
  version: "v1.4.0"
