apiVersion: v1
kind: Service
metadata:
  name: kube-dns-metrics
  namespace: kube-system
  labels:
    component: kube-dns
spec:
  selector:
    k8s-app: kube-dns
  ports:
    - name: kubedns-metrics
      port: 10055
      protocol: TCP
      targetPort: 10055
    - name: sidecar-metrics
      port: 10054
      protocol: TCP
      targetPort: 10054
