
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - svc-monitor.yaml

commonLabels:
  app: kubemq-consumer
  domain: apps
  feature: kubemq

commonAnnotations:
  version: v1.0.0
