{
 "title": "Jaeger all-in-one",
 "tags": [
  "tracing",
  "jaeger",
  "all-in-one"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "svc", "label": "Service", "query": "label_values(svc)" }
  ]
 },
 "panels": [
  {
   "title": "Jaeger Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spans Received/sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_spans_received_total[1m]))"
      }
     ]
    },
    {
     "title": "Average in-queue latency (sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jaeger_in_queue_latency_sum / jaeger_in_queue_latency_count"
      }
     ]
    },
    {
     "title": "Batch Size (spans)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jaeger_batch_size" }
     ]
    },
    {
     "title": "Queue Length (Spans)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jaeger_queue_length" }
     ]
    },
    {
     "title": "Spans Dropped/sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jaeger_spans_dropped_total[5m])"
      }
     ]
    },
    {
     "title": "Span save latency (sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jaeger_save_latency_sum / jaeger_save_latency_count"
      }
     ]
    },
    {
     "title": "trace_receive_total",
     "type": "graph",
     "description": "Trace接收总数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jaeger_traces_received_total{svc=\"$svc\"}"
      }
     ]
    },
    {
     "title": "traces_saved_by_svc_total",
     "type": "graph",
     "description": "保存Save总数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jaeger_traces_saved_by_svc_total{svc=\"$svc\"}"
      }
     ]
    },
    {
     "title": "span_received_total",
     "type": "graph",
     "description": "接收Span总数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jaeger_spans_received_total{svc=\"$svc\"}"
      }
     ]
    },
    {
     "title": "spans_saved_by_svc_total",
     "type": "graph",
     "description": "保存Span总数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jaeger_spans_saved_by_svc_total{svc=\"$svc\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jaeger Agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "jaeger_agent_thrift_udp_server_packets_processed/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_thrift_udp_server_packets_processed_total[5m])) by (protocol)"
      }
     ]
    },
    {
     "title": "avg(jaeger_agent_thrift_udp_server_packet_size)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(jaeger_thrift_udp_server_packet_size) by (protocol)"
      }
     ]
    },
    {
     "title": "jaeger_agent_thrift_udp_server_queue_size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(jaeger_thrift_udp_server_queue_size) by (protocol)"
      }
     ]
    },
    {
     "title": "jaeger_agent_thrift_udp_server_read_errors/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_thrift_udp_server_read_errors_total[5m])) by (protocol)"
      }
     ]
    },
    {
     "title": "jaeger_agent_thrift_udp_server_packets_dropped/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_thrift_udp_server_packets_dropped_total[5m])) by (protocol)"
      }
     ]
    },
    {
     "title": "jaeger_agent_thrift_udp_t_processor_handler_errors/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_thrift_udp_t_processor_handler_errors_total[5m])) by (protocol)"
      }
     ]
    },
    {
     "title": "jaeger_agent_tchannel_reporter_batches_submitted/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_agent_reporter_batches_submitted_total[5m])) by (format)"
      }
     ]
    },
    {
     "title": "jaeger_agent_tchannel_reporter_spans_submitted/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_agent_reporter_spans_submitted_total[5m])) by (format)"
      }
     ]
    },
    {
     "title": "avg(jaeger_agent_tchannel_reporter_batch_size)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(jaeger_agent_reporter_batch_size) by (format)"
      }
     ]
    },
    {
     "title": "jaeger_agent_http_server_requests/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_http_server_requests_total[5m])) by (type)"
      }
     ]
    },
    {
     "title": "jaeger_agent_tchannel_reporter_batches_failures/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_agent_reporter_batches_failures_total[5m])) by (format)"
      }
     ]
    },
    {
     "title": "jaeger_agent_tchannel_reporter_spans_failures/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_agent_reporter_spans_failures_total[5m])) by (format)"
      }
     ]
    },
    {
     "title": "jaeger_agent_http_server_errors/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_http_server_errors_total[5m])) by (source, status)",
       "legendFormat": "{{source}}.{{status}}"
      }
     ]
    },
    {
     "title": "total(jaeger_agent_collector_proxy)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jaeger_agent_collector_proxy_total) by (endpoint,protocol,result)"
      }
     ]
    }
   ]
  },
  {
   "title": "Jaeger Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average request latency (milliseconds)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(jaeger_query_latency_sum / jaeger_query_latency_count)*1000"
      }
     ]
    },
    {
     "title": "Requests/min (All requests)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_query_requests_total[5m]))*60",
       "legendFormat": "All requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{status_code=~\"2xx\"}[5m]))*60",
       "legendFormat": "2xx Requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{status_code!=\"2xx\"}[5m]))*60",
       "legendFormat": "Non-2xx Requests (/min)"
      }
     ]
    },
    {
     "title": "get-traces requests/min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"get_trace\"}[5m]))*60",
       "legendFormat": "All requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"get_trace\",result=\"ok\"}[5m]))*60",
       "legendFormat": "2xx Requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"get_trace\",result!=\"ok\"}[5m]))*60",
       "legendFormat": "Non-2xx Requests (/min)"
      }
     ]
    },
    {
     "title": "fidn-traces requests/min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"find_traces\"}[5m]))*60",
       "legendFormat": "All requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"find_traces\",result=\"ok\"}[5m]))*60",
       "legendFormat": "2xx Requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"find_traces\",result!=\"ok\"}[5m]))*60",
       "legendFormat": "Non-2xx Requests (/min)"
      }
     ]
    },
    {
     "title": "fidn-traces requests/min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"find_traces\"}[5m]))*60",
       "legendFormat": "All requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"find_traces\",result=\"ok\"}[5m]))*60",
       "legendFormat": "2xx Requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"find_traces\",result!=\"ok\"}[5m]))*60",
       "legendFormat": "Non-2xx Requests (/min)"
      }
     ]
    },
    {
     "title": "get-operations requests/min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"get_operations\"}[5m]))*60",
       "legendFormat": "All requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"get_operations\",result=\"ok\"}[5m]))*60",
       "legendFormat": "2xx Requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"get_operations\",result!=\"ok\"}[5m]))*60",
       "legendFormat": "Non-2xx Requests (/min)"
      }
     ]
    },
    {
     "title": "get-services requests/min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"get_services\"}[5m]))*60",
       "legendFormat": "All requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"get_services\",result=\"ok\"}[5m]))*60",
       "legendFormat": "2xx Requests (/min)"
      },
      {
       "expr": "sum(rate(jaeger_query_requests_total{operation=\"get_services\",result!=\"ok\"}[5m]))*60",
       "legendFormat": "Non-2xx Requests (/min)"
      }
     ]
    }
   ]
  }
 ]
}