
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubemq

resources:
  # - prom-rules.yaml
  - svc-monitor.yaml

commonLabels:
  app: kubemq
  domain: brokers
  component: monitoring

commonAnnotations:
  version: "v2.2.0"
