apiVersion: v1
kind: ConfigMap
metadata:
  name: kubemq-operator
data:
  SOURCE: "direct"
  DEBUG_MODE: "false"
  OPERATOR_NAME: "kubemq-operator"
  KUBEMQ_LICENSE_MODE: "COMMUNITY"
  
  RELATED_IMAGE_KUBEMQ_CLUSTER: "kubemq/kubemq:v2.2.0@sha256:c2d796134090e51f5fd2c59d3a80338948a1728b1d4c19844baaeefd81188034"
  CONNECTOR_TARGETS_IMAGE: "kubemq/kubemq-targets:v0.5.10@sha256:bcfc777704d0c20981f58079acbccb9d7b8c0c9468490b5fd8cc0d61c90b793e"
  CONNECTOR_SOURCES_IMAGE: "kubemq/kubemq-sources:v0.4.6@sha256:059cd199a89274d131b1cf16e2ed00a6312e54b8e9aee03179761e98f3eaf63c"
  CONNECTOR_BRIDGES_IMAGE: "kubemq/kubemq-bridges:v0.5.0@sha256:37481b790947e6e5fbc0a03f9f378e0c53c6414a6f49904c8152a17c93b5900f"
  # not in docker hub (docker.io) ?!
  CONNECTOR_TASKS_IMAGE: "kubemq/kubemq-tasks:latest"
  
  # internal monitoring
  RELATED_IMAGE_PROMETHEUS: "prom/prometheus:v2.24.0@sha256:03486e9bceffa8a58c00e84a703b6dde7d518a5a82c669c2024a7e30af017e86"
  RELATED_IMAGE_GRAFANA: "grafana/grafana:7.3.6@sha256:9469eab35aa2f92253f5839d51b5228124c4e9c5bad2fb9f62e5dac9183f21d6"
  KUBEMQ_VIEW_DASHBOARD_SOURCE: "https://raw.githubusercontent.com/kubemq-io/kubemq-dashboard/master/dashboard.json"
