apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  name: jaeger

  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.21.0
    labels:
      domain: tracing
      feature: jaeger
    # options:
    #   log-level: debug
    #   query:
    #     base-path: /jaeger
    tracingEnabled: false
    resources:
      requests:
        cpu: 1
        memory: 500M
      limits:
        cpu: 1
        memory: 500M

  # ui:
  #   options:
  #     dependencies:
  #       menuEnabled: false
  #     tracking:
  #       gaID: UA-000000-2
  #     menu:
  #       - label: About Jaeger
  #         items:
  #           - label: Documentation
  #             url: https://www.jaegertracing.io/docs/latest

  storage:
    options:
      memory:
        max-traces: 100000
