
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracing

resources:
  - jaeger_all-in-one.yaml
  # - jaeger_simple.yaml
  # - no-headless-service.yaml
  - metrics-service.yaml
  - svc-monitor.yaml

commonLabels:
  app: jaeger
  domain: tracing
  feature: jaeger

commonAnnotations:
  version: "1.21.0"
