
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracing

resources:
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - svc-monitor.yaml

commonLabels:
  app: tempo
  domain: tracing
  group: tempo

commonAnnotations:
  version: "0.4.0"
