apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: tempo
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:0.4.0@sha256:b15976a07f82ed09d2918a78c8c130b4c3656604d4b5c00e317e71832683634e
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/conf/tempo.yaml
            - -mem-ballast-size-mbs=1024
          ports:
            - name: metrics
              containerPort: 3100
            # jaeger
            # thrift-compact
            - name: jg-thrift-comp
              containerPort: 6831
              protocol: UDP
            # thrift-binary
            - name: jg-thrift-bin
              containerPort: 6832
              protocol: UDP
            - name: jg-thrift-http
              containerPort: 14268
            - name: jg-grpc
              containerPort: 14250
            # zipkin
            - name: zipkin
              containerPort: 9411
            # otlp
            - name: otlp
              containerPort: 55680
            # opencensus
            - name: opencensus
              containerPort: 55678
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /conf
            - name: traces
              mountPath: /var/tempo/traces
            - name: wal
              mountPath: /var/tempo/wal
        - name: tempo-query
          image: grafana/tempo-query:0.4.0@sha256:4e57e1904c13a6b06d3b10665a0a97d3708cfb480ec81595e34a1f36b3ef2db4
          imagePullPolicy: IfNotPresent
          args:
            - --query.base-path=/
            - --grpc-storage-plugin.configuration-file=/conf/tempo-query.yaml
          ports:
            - name: jg-ui
              containerPort: 16686
            - name: jg-metrics
              containerPort: 16687
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - mountPath: /conf
              name: query-config
      volumes:
        - configMap:
            name: tempo
          name: config
        - configMap:
            name: tempo-query
          name: query-config
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: traces
        labels:
          app: tempo
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3G
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: wal
        labels:
          app: tempo
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
