
apiVersion: core.k8s.kubemq.io/v1alpha1
kind: KubemqCluster
metadata:
  name: kubemq-cluster
spec:
  replicas: 3
  image:
    image: kubemq/kubemq:v2.2.0@sha256:c2d796134090e51f5fd2c59d3a80338948a1728b1d4c19844baaeefd81188034
    pullPolicy: IfNotPresent
  resources:
    requestsCpu: 500m
    requestsMemory: 500M
    limitsCpu: 500m
    limitsMemory: 500M
  api:
    disabled: false
  health:
    enabled: true
  # standalone: true # ?
  volume:
    size: 1G
