
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubemq

resources:
  - kubemq-cluster.yaml

commonLabels:
  app: kubemq
  domain: brokers
  component: cluster

commonAnnotations:
  version: "v2.2.0"
