{
 "title": "Kubemq Dashboard",
 "description": "Kubemq Prometheus Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Events Messages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:count:events:sum[$__range])-min_over_time(kubemq:messages:count:events:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Events Store Messages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:count:events_store:sum[$__range])-min_over_time(kubemq:messages:count:events_store:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Queue Messages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:count:queues:sum[$__range])-min_over_time(kubemq:messages:count:queues:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Queries Messages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:count:queries:sum[$__range])-min_over_time(kubemq:messages:count:queries:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Commands Messages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:count:commands:sum[$__range])-min_over_time(kubemq:messages:count:commands:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Responses Messages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:count:responses:sum[$__range])-min_over_time(kubemq:messages:count:responses:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Events Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:volume:events:sum[$__range])-min_over_time(kubemq:messages:volume:events:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Events Store Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:volume:events_store:sum[$__range])-min_over_time(kubemq:messages:volume:events_store:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Queue Messages Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:volume:queues:sum[$__range])-min_over_time(kubemq:messages:volume:queues:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Queries Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:volume:queries:sum[$__range])-min_over_time(kubemq:messages:volume:queries:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Commands Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:volume:commands:sum[$__range])-min_over_time(kubemq:messages:volume:commands:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Responses Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:volume:responses:sum[$__range])-min_over_time(kubemq:messages:volume:responses:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Events Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:errors:events:sum[$__range])-min_over_time(kubemq:messages:errors:events:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Events Store Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:errors:events_store:sum[$__range])-min_over_time(kubemq:messages:errors:events_store:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Queue Messages Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:errors:queues:sum[$__range])-min_over_time(kubemq:messages:errors:queues:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Queries Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:errors:queries:sum[$__range])-min_over_time(kubemq:messages:errors:queries:sum[$__range])"
    }
   ]
  },
  {
   "title": "Total Commands Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:errors:commands:sum[$__range])-min_over_time(kubemq:messages:errors:commands:sum[$__range]) "
    }
   ]
  },
  {
   "title": "Total Responses Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(kubemq:messages:errors:responses:sum[$__range])-min_over_time(kubemq:messages:errors:responses:sum[$__range])"
    }
   ]
  },
  {
   "title": "Incoming Messages  Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Messages per second" }
   ],
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:events:send:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Events"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:count:events_store:send:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Events Store"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:count:queues:send:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Queues"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:count:queries:send:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:count:commands:send:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Incoming Volume Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "bps", "label": "Bits per second" }
   ],
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:events:send:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Events"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:events_store:send:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Events Store"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:queues:send:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Queues"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:queries:send:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:commands:send:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Outgoing Messages  Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Messages per second" }
   ],
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:events:receive:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Events"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:count:events_store:receive:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Events Store"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:count:queues:receive:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Queues"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:count:queries:receive:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:count:commands:receive:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Outgoing Volume Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "bps", "label": "Bytes per second" }
   ],
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:events:receive:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Events"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:events_store:receive:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Events Store"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:queues:receive:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Queues"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:queries:receive:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:commands:receive:sum[$__range]) OR on() vector(0))",
     "legendFormat": "Commands"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Incoming Events Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "repeat": "messagetype",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:events:send:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Events Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:events:send:sum[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Events Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:events:receive:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Events Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:events:receive:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"events\"}) by(client_id,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"events\"}) by(client_id,side) "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"events\"}) by(channel,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"events\"}) by(channel,side) "
    }
   ]
  },
  { "title": "Events Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Incoming Events Store Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:events_store:send:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Events Store Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:events_store:send:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Events Store Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:events_store:receive:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Events Store Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:events_store:receive:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"events_store\"}) by(client_id,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"events_store\"}) by(client_id,side) "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"events_store\"}) by(channel,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"events_store\"}) by(channel,side) "
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Incoming Queues Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:queues:send:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Queues Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 59 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:queues:send:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Queues Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:queues:receive:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Queues Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 59 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:queues:receive:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"queues\"}) by(client_id,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"queues\"}) by(client_id,side) "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"queues\"}) by(channel,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"queues\"}) by(channel,side) "
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Incoming Queries Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 76 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:queries:send:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Queries Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 76 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:queries:send:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Queries Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 76 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:queries:receive:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Queries Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 76 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:queries:receive:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"queries\"}) by(client_id,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"queries\"}) by(client_id,side) "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"queries\"}) by(channel,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"queries\"}) by(channel,side) "
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Incoming Commands Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 93 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:commands:send:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Commands Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 93 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:commands:send:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Commands Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 93 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:count:commands:receive:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Commands Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 93 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(irate(kubemq:messages:volume:commands:receive:sum[$__range]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"commands\"}) by(client_id,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"commands\"}) by(client_id,side) "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"commands\"}) by(channel,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"commands\"}) by(channel,side) "
    }
   ]
  }
 ]
}