
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reloader

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - svc-monitor.yaml

commonLabels:
  app: reloader
  domain: support
  group: reloader

commonAnnotations:
  version: v0.0.76
