apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reloader
spec:
  selector:
    matchLabels:
      app: reloader
  namespaceSelector:
    matchNames:
      - reloader
  endpoints:
    - port: http
      interval: 15s
      scrapeTimeout: 14s
