apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grpc-server
spec:
  selector:
    matchLabels:
      app: grpc-server
  namespaceSelector:
    matchNames:
      - apps
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 14s
