
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubemq

resources:
  - operator-rbac.yaml
  - cluster-rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - svc-monitor.yaml

commonLabels:
  app: kubemq-operator
  domain: brokers
  group: operators
  feature: kubemq
  component: controller

commonAnnotations:
  version: "v1.4.0"
