apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubemq-operator
spec:
  selector:
    matchLabels:
      app: kubemq-operator
  namespaceSelector:
    matchNames:
      - kubemq
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 14s
