
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - secret.yaml
  - statefulset.yaml
  - service.yaml
  - svc-monitor.yaml

commonLabels:
  app: loki
  domain: logging
  group: loki

commonAnnotations:
  version: "2.1.0"
